componentDefaultConfig:
  SecurityAnalysisFactory: com.powsybl.security.SecurityAnalysisFactoryImpl
  ContingenciesProviderFactory: com.powsybl.contingency.dsl.GroovyDslContingenciesProviderFactory

load-flow:
  default-impl-name: "OpenLoadFlow"

security-analysis:
  default-impl-name: "OpenLoadFlow"
