name: Release CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11

    - name: Package
      run: |
        mvn --batch-mode package
        echo "MAVEN_PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: powsybl-distribution-${{ env.MAVEN_PROJECT_VERSION }}
        path: target/powsybl-distribution-${{ env.MAVEN_PROJECT_VERSION }}
