name: Snapshot CI

on: [push]

jobs:
  build:
    name: Package
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Checkout core sources
      uses: actions/checkout@v3
      with:
        repository: powsybl/powsybl-core
        ref: refs/heads/main

    - name: Build and install core
      run: mvn --batch-mode -DskipTests=true --file powsybl-core/pom.xml install

    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Package
      run: mvn --batch-mode package
      
#    - name: Upload artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: powsybl-distribution-2023.1.0
#        path: target/powsybl-distribution-2023.1.0
